### ISSUE TITLE
The 0.0.2 version from rubygems.org is incomplete

### ISSUE THREAD

**Issue by allen13** [kristianmandrup/jquery-ui-bootstrap-rails#1]
When using the 0.0.2 version from rubygems none of the assets were present. Fixed the issue by using the 0.0.1 version from github.

**Comment by kristianmandrup** [comment]
Did you try using the github verion of 0.0.2 ? I will check it out ASAP. Thanks for the notice

**Comment by allen13** [comment]
No, it defaulted to 0.0.1. Didn't bother forcing it to 0.0.2.

**Comment by oneiros** [comment]
I have been looking closely at this for quite some time now and I am still not sure if I am missing something or not.

But as far as I can see, the gem on rubygems.org is a completely different project. See

http://rubygems.org/gems/jquery-ui-bootstrap-rails

and

https://github.com/jaimie-van-santen/jquery-ui-bootstrap-rails

If I am correct, how about trying to merge those two projects or choosing a different name?

**Comment by kristianmandrup** [comment]
just fork whichever one you like, merge them any way you want and assign a new name. I don't care. I can't even remember how or why I started this gem. I create so many gems I loose track. But this is all organic development as it should be. I would happily delete this project if you create a better version ;)
