### ISSUE TITLE
rename gem?

### ISSUE THREAD

**Issue by ohadlevy** [kristianmandrup/jquery-ui-bootstrap-rails#3]
Hi,

Since there is another gem with the same name, when using rubygems I'm not getting your gem.

is there a a chance to rename the gem, so its easier to consume (instead of using git refs).

thanks!

**Comment by kristianmandrup** [comment]
I recommend you fork this gem. Change it to use bundler for gem management (jeweler is DEAD!) and then post it under a new name. Thanks!
