### ISSUE TITLE
Asset depends on 'ui-bootstrap/custom-theme/ui-bg_glass_75_ffffff_1x400.png'

### ISSUE THREAD

**Issue by jsantos** [kristianmandrup/jquery-ui-bootstrap-rails#7]
When using the  gem [sprockets_better_errors](https://github.com/schneems/sprockets_better_errors) gem, the following warning is displaying, mentioning something is missing from one of the library files:

```
Sprockets::Rails::Helper::DependencyError at /
Asset depends on 'ui-bootstrap/custom-theme/ui-bg_glass_75_ffffff_1x400.png' to generate properly but has not declared the dependency
Please add: `//= depend_on_asset "ui-bootstrap/custom-theme/ui-bg_glass_75_ffffff_1x400.png"` to '/Users/jsantos/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/bundler/gems/jquery-ui-bootstrap-rails-47957c2250ee/vendor/assets/stylesheets/ui-bootstrap/jquery-ui-bootstrap.latest.css.scss'
  (in /Users/jsantos/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.
```

I'm using the following gems as well: 

```
gem 'jquery-rails'
gem 'jquery-ui-rails'
```

And on my CSS manifest, application.css:

```
 *
 *= require_self
 *= require ui-bootstrap/jquery-ui-bootstrap.latest
 *= require_tree .
 */
```

When I deploy my code to production, after asset precompilation the mentioned file does not show up, as warned by sprockets_better_errors. The icons are missing.

Am I missing something obvious here?

**Comment by kristianmandrup** [comment]
Cool :) The error msg says what you have to do:

```
Please add: `//= depend_on_asset "ui-bootstrap/custom-theme/ui-bg_glass_75_ffffff_1x400.png"` to '/Users/jsantos/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/bundler/gems/jquery-ui-bootstrap-rails-47957c2250ee/vendor/assets/stylesheets/ui-bootstrap/jquery-ui-bootstrap.latest.css.scss'
```

Which means that this gem needs to be updated with 

`//= depend_on_asset "ui-bootstrap/custom-theme/ui-bg_glass_75_ffffff_1x400.png`

I guess you should put this in `vendor/assets/stylesheets/ui-bootstrap/jquery-ui-bootstrap.latest.css.scss'`

I have never seen this `depend_on_asset` before. I guess it's a new optimization in sprockets? 

https://github.com/FortAwesome/font-awesome-sass/pull/13
https://github.com/rails/sprockets-rails/pull/96

Please fork and add this, test and make it work... then make a pull request ;) thanks!

**Comment by jsantos** [comment]
Hi,

Well, I figured these kinds of errors when I started using this gem (funny thing). But usually I just need to include that kind of //= depend_of_asset if I have a js.erb/css.erb which mentions assets imported through ruby helpers... Maybe it's not the only situation!

I'll try it out and will create a pull request for it ;)

**Comment by kristianmandrup** [comment]
Tried pushing to rubygems

```
$ bundle exec rake release
Committing jquery-ui-bootstrap-rails.gemspec
Pushing master to origin
Generated: jquery-ui-bootstrap-rails.gemspec
jquery-ui-bootstrap-rails.gemspec is valid.
  Successfully built RubyGem
  Name: jquery-ui-bootstrap-rails
  Version: 0.1.1
  File: jquery-ui-bootstrap-rails-0.1.1.gem
Executing "gem push ./pkg/jquery-ui-bootstrap-rails-0.1.1.gem":
gem push ./pkg/jquery-ui-bootstrap-rails-0.1.1.gem
Pushing gem to https://rubygems.org...
You do not have permission to push to this gem.
```

You are welcome to take over as owner/maintainer if you like ;)
